// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hubdmukhqlqsldonqrat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YmRtdWtocWxxc2xkb25xcmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0Mjc2MDgsImV4cCI6MjA1MjAwMzYwOH0.zUyNjmKV8IndVbHkBg9sC9FJKqd4D5mAmDz9QPeJExQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);